"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)&@3vh1pji-&04m+(n4ep1($=1gy04fk27=pk_z631kqa+$yve'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'user',
    'apps.book',
    'apps.school',
    'apps.massage',
    'apps.logoped',
    'apps.event',
    'apps.about_us',
    'apps.activity',
    'apps.main',
    'apps.advice',
    'apps.article',
    'apps.childDevelopment',
    'apps.recipe',
    'apps.survey',
    'apps.catalog',
    'apps.restaurant',
    'apps.club',
    'apps.sport',
    'apps.kindergarten',
    'django_summernote',
    #'ckeditor',
    'ai_help',

]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|", "bold", "italic", "link", "underline",
            "|", "bulletedList", "numberedList", "|", "blockQuote", "codeBlock",
            "|", "insertTable", "|", "undo", "redo",
        ],
        "language": "ru",
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

import os

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('ru', 'Russian'),
    ('kk', 'Kazakh'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kairatbekmuratovvv@gmail.com'
EMAIL_HOST_PASSWORD = 'bedu jzfi cter tjny'
DEFAULT_FROM_EMAIL = 'kairatbekmuratovvv@gmail.com'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

GOOGLE_MAPS_API_KEY = 'AIzaSyCSGkHrOCjab82WAhhlPayKqkzJ5MV0qlI'
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB

# JAZZMIN_SETTINGS = {
#     "site_title": "DamuWay Admin",
#     "site_header": "Панель управления DamuWay 👶💡",
#     "site_brand": "DamuWay",
#     "site_logo": "images/logo.png",
#     "site_logo_classes": "img-circle",
#     "welcome_sign": "Добро пожаловать в мир заботы о детях 🌿",
#     "copyright": "© 2025 DamuWay",
#     "search_model": ["users.CustomUser", "books.Book"],
#
#     "user_avatar": "profile.avatar",
#
#     "topmenu_links": [
#         {"name": "Главная", "url": "/", "new_window": True, "icon": "fas fa-home"},
#         {"model": "auth.User"},
#         {"model": "books.Book"},
#     ],
#
#     "usermenu_links": [
#         {"name": "Поддержка", "url": "https://t.me/damuway_admin", "new_window": True, "icon": "fas fa-life-ring"},
#     ],
#
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "books": "fas fa-book",
#         "massage": "fas fa-spa",
#         "kindergarten": "fas fa-school",
#         "school": "fas fa-chalkboard-teacher",
#         "restaurant": "fas fa-utensils",
#         "sports": "fas fa-dumbbell",
#     },
#
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "hide_apps": [],
#     "hide_models": [],
#     "order_with_respect_to": ["books", "school", "kindergarten", "massage", "sports", "restaurant"],
#
#     "custom_css": "css/admin_custom.css",
#     "custom_js": None,
#     "related_modal_active": True,
#
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",
# }
# JAZZMIN_UI_TWEAKS = {
#     "show_ui_builder": False,
#     "navbar_fixed": True,
#     "footer_fixed": False,
# }
#
# JAZZMIN_SETTINGS["custom_links"] = {
#     "users": [{
#         "name": "💬 Обратная связь",
#         "url": "https://t.me/damuway_admin",
#         "icon": "fas fa-paper-plane",
#         "permissions": ["auth.view_user"]
#     }]
# }
# JAZZMIN_SETTINGS["custom_js"] = "js/admin_message.js"
# JAZZMIN_SETTINGS["show_ui_builder"] = False
# JAZZMIN_SETTINGS["copyright"] = "С любовью 💜 от команды DamuWay"