# Generated by Django 5.2 on 2025-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='districts/'),
        ),
        migrations.AddField(
            model_name='district',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
