# Generated by Django 5.2 on 2025-04-08 07:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('age_group', models.CharField(choices=[('0-6', '0-6 месяцев'), ('6-12', '6-12 месяцев'), ('1-3', '1-3 года'), ('3-6', '3-6 лет'), ('6+', '6+ лет')], default='1-3', max_length=10, verbose_name='Возрастная группа')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('instructions', models.TextField(verbose_name='Способ приготовления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение (файл)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Изображение (ссылка)')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_recipe', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe.recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipe.recipe', verbose_name='Рецепт')),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
