# Generated by Django 5.2 on 2025-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Фото события')),
                ('category', models.CharField(choices=[('festival', 'Фестиваль'), ('workshop', 'Мастер-класс'), ('exhibition', 'Выставка'), ('concert', 'Концерт'), ('theater', 'Театр'), ('sport', 'Спорт'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('age_limit', models.CharField(default='0+', max_length=10, verbose_name='Возрастное ограничение')),
                ('price', models.CharField(default='Бесплатно', max_length=50, verbose_name='Цена')),
                ('ticket_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на билеты')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организатор')),
            ],
        ),
    ]
