# Generated by Django 5.2 on 2025-04-06 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория массажа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MassageCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название центра')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('categories', models.ManyToManyField(related_name='centers', to='massage.massagecategory', verbose_name='Виды массажа')),
            ],
        ),
        migrations.CreateModel(
            name='MassagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Ссылка на фото')),
                ('massage_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='massage.massagecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('rating', models.IntegerField(verbose_name='Оценка (1-5)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('massage_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='massage.massagecenter')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя специалиста')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Фото специалиста')),
                ('massage_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='massage.massagecenter')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='massage.massagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время сеанса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_appointments', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='massage.massagecategory')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='massage.specialist')),
            ],
        ),
    ]
