# Generated by Django 5.2 on 2025-04-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logoped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('specialization', models.CharField(choices=[('Дислалия', 'Дислалия'), ('Дизартрия', 'Дизартрия'), ('Заикание', 'Заикание'), ('Афазия', 'Афазия'), ('Общий', 'Общий логопед')], max_length=50, verbose_name='Специализация')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт (лет)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logopeds/', verbose_name='Фото')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за час (₸)')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('pending', 'В ожидании')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_logoped', to=settings.AUTH_USER_MODEL)),
                ('logoped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logoped.logoped')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age_group', models.CharField(choices=[('3-5', '3-5 лет'), ('6-8', '6-8 лет'), ('9-12', '9-12 лет')], max_length=10, verbose_name='Возраст ребенка')),
                ('date', models.DateField(verbose_name='Дата сеанса')),
                ('time', models.TimeField(verbose_name='Время сеанса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logoped_appointments', to=settings.AUTH_USER_MODEL)),
                ('logoped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='logoped.logoped')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logoped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logoped.logoped')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logoped_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20, verbose_name='День недели')),
                ('time_slot', models.CharField(max_length=20, verbose_name='Время')),
                ('logoped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='logoped.logoped')),
            ],
        ),
    ]
