# Generated by Django 5.2 on 2025-04-08 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(choices=[(1, '1 месяцев'), (2, '2 месяцев'), (3, '3 месяцев'), (4, '4 месяцев'), (5, '5 месяцев'), (6, '6 месяцев'), (7, '7 месяцев'), (8, '8 месяцев'), (9, '9 месяцев'), (10, '10 месяцев'), (11, '11 месяцев'), (12, '12 месяцев'), (13, '13 месяцев'), (14, '14 месяцев'), (15, '15 месяцев'), (16, '16 месяцев'), (17, '17 месяцев'), (18, '18 месяцев'), (19, '19 месяцев'), (20, '20 месяцев'), (21, '21 месяцев'), (22, '22 месяцев'), (23, '23 месяцев'), (24, '24 месяцев'), (25, '25 месяцев'), (26, '26 месяцев'), (27, '27 месяцев'), (28, '28 месяцев'), (29, '29 месяцев'), (30, '30 месяцев'), (31, '31 месяцев'), (32, '32 месяцев'), (33, '33 месяцев'), (34, '34 месяцев'), (35, '35 месяцев'), (36, '36 месяцев'), (37, '37 месяцев'), (38, '38 месяцев'), (39, '39 месяцев'), (40, '40 месяцев'), (41, '41 месяцев'), (42, '42 месяцев'), (43, '43 месяцев'), (44, '44 месяцев'), (45, '45 месяцев'), (46, '46 месяцев'), (47, '47 месяцев'), (48, '48 месяцев'), (49, '49 месяцев'), (50, '50 месяцев'), (51, '51 месяцев'), (52, '52 месяцев'), (53, '53 месяцев'), (54, '54 месяцев'), (55, '55 месяцев'), (56, '56 месяцев'), (57, '57 месяцев'), (58, '58 месяцев'), (59, '59 месяцев'), (60, '60 месяцев'), (61, '61 месяцев'), (62, '62 месяцев'), (63, '63 месяцев'), (64, '64 месяцев'), (65, '65 месяцев'), (66, '66 месяцев'), (67, '67 месяцев'), (68, '68 месяцев'), (69, '69 месяцев'), (70, '70 месяцев'), (71, '71 месяцев'), (72, '72 месяцев')], unique=True, verbose_name='Возраст (месяцев)')),
                ('physical', models.TextField(verbose_name='Физическое развитие')),
                ('speech', models.TextField(verbose_name='Речевое развитие')),
                ('emotional', models.TextField(verbose_name='Эмоциональное развитие')),
                ('social', models.TextField(verbose_name='Социальное развитие')),
                ('recommendations', models.TextField(verbose_name='Рекомендации родителям')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Изображение (ссылка)')),
                ('source', models.URLField(blank=True, null=True, verbose_name='Источник информации')),
            ],
            options={
                'verbose_name': 'Этап развития',
                'verbose_name_plural': 'Развитие ребенка по возрасту',
                'ordering': ['age'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='childDevelopment.childdevelopment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Development_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
