# Generated by Django 5.2 on 2025-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('url', models.CharField(help_text="Например: 'schools' для /schools/", max_length=100, verbose_name='URL раздела')),
            ],
        ),
    ]
