# Generated by Django 5.2 on 2025-04-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('sport_type', models.CharField(choices=[('boxing', 'Бокс'), ('judo', 'Дзюдо'), ('karate', 'Каратэ'), ('swimming', 'Плавание'), ('football', 'Футбол'), ('gymnastics', 'Гимнастика'), ('taekwondo', 'Тхэквондо'), ('basketball', 'Баскетбол'), ('wrestling', 'Борьба')], max_length=50)),
                ('min_age', models.PositiveIntegerField(default=5)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField(default=0, help_text='Цена за месяц в тенге')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsClubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sport.sportsclub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
